/*ADD_INT:
        > SRC0_SEL.GPR(0) SRC1_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_Y SRC1_CHAN.CHAN_X LAST;
        > WRITE_MASK DST_GPR(1);
        > 0x0000BEEF;
        > 0x00000000;

MEM_RD_SCRATCH:
		MEM_RD_WORD0> ELEM_SIZE(3) FETCH_WHOLE_QUAD SRC_SEL_X.SEL_X;

MEM_RD_SCRATCH:
		MEM_RD_WORD0> ELEM_SIZE(0) FETCH_WHOLE_QUAD SRC_SEL_X.SEL_W;
*/
ADD_INT:
        ALU_WORD0> SRC0_SEL.GPR(0) SRC1_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_W SRC1_CHAN.CHAN_X LAST;
        ALU_WORD1_OP2> WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_X;
        LITERAL> 0xDEADBEEF;
        LITERAL> 0x00000000;

ADD_INT:
        ALU_WORD0> SRC0_SEL.GPR(0) SRC1_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_W SRC1_CHAN.CHAN_X LAST;
        ALU_WORD1_OP2> WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_Y;
        LITERAL> 0xEFBEADDE;
        LITERAL> 0x00000000;

ADD_INT:
        ALU_WORD0> SRC0_SEL.GPR(0) SRC1_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_X SRC1_CHAN.CHAN_X LAST;
        ALU_WORD1_OP2> WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_Z;
        LITERAL> 0x0000DEAD;
        LITERAL> 0x00000000;

ADD_INT:
        ALU_WORD0> SRC0_SEL.GPR(0) SRC1_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_Y SRC1_CHAN.CHAN_X LAST;
        ALU_WORD1_OP2> WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_W;
        LITERAL> 0x0000BEEF;
        LITERAL> 0x00000000;
end;
