ADD_INT:
        > SRC0_SEL.GPR(0) SRC1_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_Y SRC1_CHAN.CHAN_X LAST;
        > WRITE_MASK DST_GPR(1);
        > 0x0000BEEF;
        > 0x00000000;

MEM_RD_SCRATCH:
		MEM_RD_WORD0> ELEM_SIZE(4) FETCH_WHOLE_QUAD SRC_SEL_X.SEL_X;

MEM_RD_SCRATCH:
		MEM_RD_WORD0> ELEM_SIZE(1) FETCH_WHOLE_QUAD SRC_SEL_X.SEL_W;

end;
